services:
  - type: web
    name: hr-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn hr_api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        sync: false
    plan: free

  - type: web
    name: hr-dashboard
    runtime: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: IS_TEMPLATE
        value: false
    plan: free