name: Scheduled ETL Refresh

on:
  # schedule:
  #  - cron: "0 6 * * *"  # Runs every day at 6 AM UTC
  workflow_dispatch:     # Allows manual triggering from GitHub UI

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL script
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        IS_TEMPLATE: "true"
      run: python etl/run_etl.py